executable              = submit_DCTR_notebook_training_showered_regular_epochs.sh

arguments               = $(Process)

log                     = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).log
output                  = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).out
error                   = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).err

request_cpus            = 4
request_gpus            = 1

request_memory          = 32G
+RequestRuntime         = 100000

queue 5
