executable              = submit_DCTR_training_NNLO_MSE_vs_BCE.sh

arguments               = $(Process)

log                     = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).log
output                  = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).out
error                   = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).err

request_cpus            = 4
request_gpus            = 1

request_memory          = 32G
+RequestRuntime         = 100000

queue 24
