executable              = submit_training.sh

arguments               = $(Process)

log                     = logs/submit_training_v2_$(Process).log
output                  = logs/submit_training_v2_$(Process).out
error                   = logs/submit_training_v2_$(Process).err

request_cpus            = 4
request_gpus            = 1
request_memory          = 16G
+RequestRuntime         = 40000

queue 10
