executable              = submit_MiNNLO_HadronLevelAll-Off_FSR-Off_MPI-Off.sh

arguments               = $(Process)

log                     = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).log
output                  = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).out
error                   = logs/$(SUBMIT_FILE)_$(Process)_$(SUBMIT_TIME).err

request_cpus            = 4
request_memory          = 16G
+RequestRuntime         = 20000

queue 1000
